### ISSUE TITLE
Design: Understand 2

### ISSUE THREAD

**Issue by ncsQuan** [ai-conversation-coach/convo-guru#11]
Meet with developer team leads
- review existing material compiled by developers
- define the problem
- compile features list

**Comment by nninanguyenn** [comment]
Review existing material compiled by developers:
- Created initial prototype for landing page and chat interface in Figma
          - Additionally created mobile version
- Firebase Authentication is set up
- Database created with MongoDB Atlas

Define the problem:
- The problem that the AI Conversation Coach app aims to solve is the improvement of users' conversation skills and confidence. 
- The AI Conversation Coach app seeks to address these challenges by providing users with a personalized and interactive platform to practice and enhance their conversation skills. 

Compile features list:
- Personalized Coaching Sessions: Tailored coaching sessions based on the user's skill level, interests, and goals.
- Real-time Feedback: Instant feedback on user responses during practice conversations, highlighting areas for improvement and providing suggestions.
- Progress Tracking and Analytics: Tracking of user progress over time, including visualization of performance data and personalized insights.
- Accessibility Features: Support for multiple languages, dialects, and accessibility options to accommodate diverse user needs and preferences.
- Data Privacy and Security: Implementation of data privacy measures to protect user information and ensure compliance with relevant regulations.
